name: Lint Markdown
on: [push, pull_request]
jobs:
  mdlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: markdownlint-cli
        uses: actionshub/markdownlint@main
